
[functions.auth-signin]
enabled = true
verify_jwt = true
import_map = "./functions/auth-signin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/auth-signin/index.ts"
